version: '3'

services:
  webserver:
    build:
      context:    ./webserver/build
      dockerfile: Dockerfile
    command: airflow webserver
    environment:
      AIRFLOW_HOME: "/airflow"
    volumes:
      - "./webserver/data:/airflow"
    ports:
      - 18080:8080
    networks:
      - backend
    depends_on:
      - postgres
      - redis
  scheduler:
    build:
      context:    ./scheduler/build
      dockerfile: Dockerfile
    command: airflow scheduler
    environment:
      AIRFLOW_HOME: "/airflow"
    volumes:
      - "./scheduler/data:/airflow"
    networks:
      - backend
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_USER:     "airflow"
      POSTGRES_PASSWORD: "airflow" # override in docker-compose.override.yml
      POSTGRES_DB:       "airflow"
    volumes:
      - "./postgres/data:/var/lib/postgresql/data"
    networks:
      - backend
  redis:
    image: redis:3.2-alpine
    volumes:
      - "./redis/data:/data"
    networks:
      - backend

networks:
  backend:
